apiVersion: v1
kind: Service
metadata:
  name: housing-price-service
  labels:
    app: housing-price-api
spec:
  type: LoadBalancer
  selector:
    app: housing-price-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http